import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :wa7vc, Wa7vcWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PhxExample.Finch

# Do not print debug messages in production
# Also enable the Sentry backend for capturing logger data
config :logger,
  level: :info,
  backends: [:console, Sentry.LoggerBackend]

# Include the path to a cache manifest containing the digested version of static files.
# This manifest is generated by the `mix phx.digest` task, which you should run after
# static files are built and before starting your production server.
config :wa7vc, Wa7vcWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Include the Application version on the endpoint for accessing later and issuing
# "Website has been updated" notifications to users
# TODO: Do we need? This doesn't seem to be used?
config :wa7vc, Wa7vcWeb.Endpoint, version: Application.spec(:wa7vc, :vsn)

# Include Sentry configuration specific to production, but not dependent on
# runtime variables
config :sentry,
  environment_name: :prod,
  tags: %{
    env: "production"
  },
  release: "wa7vc@#{Application.spec(:wa7vc, :vsn)}"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
