FROM docker.io/hexpm/elixir:1.12.3-erlang-24.1.7-debian-buster-20210902-slim as builder
RUN mix local.rebar --force && \
    mix local.hex --force
WORKDIR /app
ENV MIX_ENV=prod
COPY mix.* /app/
RUN mix deps.get --only prod
RUN mix deps.compile

FROM builder as releaser
ENV MIX_ENV=prod
COPY . /app/
RUN mix release && \
  cd _build/prod/rel/marvin && \
  tar czf /opt/marvin.tar.gz .
