all:
  children:
    webservers:
      hosts:
        app-tx-02.inf.daedalusdreams.com:
          ansible_port: 62222
          ansible_user: wa7vc
    marvinserver:
      hosts:
        app-tx-02.inf.daedalusdreams.com:
          ansible_port: 62222
          ansible_user: wa7vc
