---
# Designed to run on a DaedalusDreams app server config, not found here, that is expecting this app.
# Because of that this isn't a full config, it simply places the needed config into the deploy user's directory, where the system is expecting it.
# Most likely you want to run with "--tags marvin" or "--tags wa7vc" to rebuild and redeploy that app.
# Use the tag "deploy" to execute the deploy steps after manually building the release

- name: include encrypted secret values for production server
  include_vars: secrets.yml

- name: Generic preparations
  tags: [ generic ]
  hosts: app1.daedalusdreams.com
  tasks:
    - name: ensure latest versions of files uploaded
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: 'wa7vc.org_nginx-sites-enabled',dest: '/home/wa7vc/wa7vc.org-nginx-sites-enabled'}
        - {src: 'error_page',dest: '/home/wa7vc/error_page'}


- name: deploy latest version of Marvin
  tags: [ marvin ]
  hosts: app1.daedalusdreams.com
  tasks:
    - name: Build latest release locally
      tags: [ build ]
      shell:
        chdir: apps/marvin/
        cmd: ./release.sh
    - name: Copy release to server
      tags: [ deploy ]
      copy:
        src: apps/marvin/tmp/marvin.tar.gz
        dest: "/home/wa7vc/marvin.tar.gz"
    - name: stop Marvin systemd unit on server
      tags: [ deploy ]
      systemd:
        name: marvin
        state: stopped
    - name: update Marvin systemd unit file (And notify systemd to re-read it if necessary)
      tags: [ deploy ]
      template:
        src: "marvin_systemd_file.j2"
        dest: "marvin_systemd_unit"
      notify: reload systemd
    - name: replace existing Marvin code with new release
      tags: [ deploy ]
      unarchive:
        src: marvin.tar.gz
        dest: /home/wa7vc/apps/marvin/
    #- name: Run migrations
      #shell: './marvin/bin/marvin eval "Marvin.ReleaseTasks.migrate()"'
    - name: start Marvin systemd unit on server
      tags: [ deploy ]
      systemd:
        name: marvin
        state: started

- name: deploy latest version of Wa7vc (web)
  tags: [ wa7vc ]
  hosts: app1.daedalusdreams.com
  tasks:
    - name: Build latest release locally
      tags: [ build ]
      shell:
        chdir: apps/wa7vc/
        cmd: ./release.sh
    - name: Copy release to server
      tags: [ deploy ]
      copy:
        src: apps/wa7vc/tmp/wa7vc.tar.gz
        dest: "/home/wa7vc/wa7vc.tar.gz"
    - name: stop systemd unit on server
      tags: [ deploy ]
      systemd:
        name: wa7vc
        state: stopped
    - name: update systemd unit file (And notify systemd to re-read it if necessary)
      tags: [ deploy ]
      template:
        src: "wa7vc_systemd_file.j2"
        dest: "wa7vc_systemd_unit"
      notify: reload systemd
    - name: replace existing code with new release
      tags: [ deploy ]
      unarchive:
        src: /home/wa7vc/wa7vc.tar.gz
        dest: /home/wa7vc/apps/wa7vc/
    #- name: Run migrations
      #shell: '/home/wa7vc/apps/wa7vc/bin/wa7vc eval "Wa7vc.ReleaseTasks.migrate()"'
    - name: start systemd unit on server
      tags: [ deploy ]
      systemd:
        name: wa7vc
        state: started
